/**
 * AUTO-GENERATED FILE — DO NOT EDIT.
 *
 * Source: Postgres catalogs (schema: cubefsrs)
 * Generated by: oosync/src/codegen-schema.ts
 */

import type { BrowserSqliteDatabase } from "oosync/runtime/browser-sqlite";
import { createBrowserSqliteClient } from "oosync/runtime/browser-sqlite";
// eslint-disable-next-line import/no-unresolved
import sqlWasmUrl from "sql.js/dist/sql-wasm.wasm?url";
import * as schema from "../../../drizzle/schema-sqlite";
import { browserSqliteHooks } from "./oosync-browser-sqlite-hooks";
import {
	SYNCABLE_TABLES,
	TABLE_REGISTRY,
	TABLE_SYNC_ORDER,
	TABLE_TO_SCHEMA_KEY,
} from "../../../shared/table-meta";

export const browserSqliteClient = createBrowserSqliteClient({
	schema,
	syncPushQueue: schema.syncPushQueue,
	syncSchema: {
		syncableTables: SYNCABLE_TABLES,
		tableRegistry: TABLE_REGISTRY,
		tableSyncOrder: TABLE_SYNC_ORDER,
		tableToSchemaKey: TABLE_TO_SCHEMA_KEY,
	},
	sqlWasmUrl,
	hooks: browserSqliteHooks,
	diagnosticsEnabled: import.meta.env.VITE_SYNC_DIAGNOSTICS === "true",
	storage: {
		indexedDbName: "cubefsrs-storage",
		indexedDbStore: "databases",
		dbKeyPrefix: "cubefsrs-db",
		dbVersionKeyPrefix: "cubefsrs-db-version",
		outboxBackupKeyPrefix: "cubefsrs-outbox-backup",
		lastSyncTimestampKeyPrefix: "CF_LAST_SYNC_TIMESTAMP",
	},
	databaseVersion: 1,
	schemaVersion: "1.0.0",
	migrationFiles: ["/drizzle/migrations/sqlite/0000_sticky_riptide.sql"],
	forceResetQueryParams: [
		{ key: "reset", value: "true" },
		{ key: "migrate", value: "uuid" },
	],
	testConfig: {},
});

export const initializeDb = browserSqliteClient.initializeDb;
export const getDb = browserSqliteClient.getDb;
export const persistDb = browserSqliteClient.persistDb;
export const closeDb = browserSqliteClient.closeDb;
export const clearDb = browserSqliteClient.clearDb;
export const setupAutoPersist = browserSqliteClient.setupAutoPersist;
export const getSqliteInstance = browserSqliteClient.getSqliteInstance;
export const getSqlJsDebugInfo = browserSqliteClient.getSqlJsDebugInfo;
export const getClientSqliteDebugState = browserSqliteClient.getDebugState;
export const loadOutboxBackupForUser =
	browserSqliteClient.loadOutboxBackupForUser;
export const clearOutboxBackupForUser =
	browserSqliteClient.clearOutboxBackupForUser;

export { schema };
export type SqliteDatabase = BrowserSqliteDatabase;
export type Schema = typeof schema;
