/**
 * AUTO-GENERATED FILE — DO NOT EDIT.
 *
 * Source: Postgres catalogs (schema: cubefsrs)
 * Generated by: oosync/src/codegen-schema.ts
 */

import {
	index,
	integer,
	primaryKey,
	real,
	sqliteTable,
	text,
	uniqueIndex,
} from "drizzle-orm/sqlite-core";
import { sqliteSyncColumns } from "oosync/shared/sync-columns";

export const algCase = sqliteTable(
	"alg_case",
	{
		id: text("id")
			.notNull()
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		slug: text("slug").notNull(),
		subsetId: text("subset_id")
			.notNull()
			.references(() => algSubset.id),
		userId: text("user_id"),
		name: text("name").notNull(),
		alg: text("alg").notNull(),
		sortOrder: integer("sort_order").default(0),
		createdAt: text("created_at").$defaultFn(() => new Date().toISOString()),
		updatedAt: text("updated_at").$defaultFn(() => new Date().toISOString()),
	},
	(t) => [uniqueIndex("alg_case_slug_user_id_key").on(t.slug, t.userId)],
);

export const algCategory = sqliteTable(
	"alg_category",
	{
		id: text("id")
			.notNull()
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		slug: text("slug").notNull(),
		userId: text("user_id"),
		name: text("name").notNull(),
		sortOrder: integer("sort_order").default(0),
		createdAt: text("created_at").$defaultFn(() => new Date().toISOString()),
	},
	(t) => [uniqueIndex("alg_category_slug_user_id_key").on(t.slug, t.userId)],
);

export const algSubset = sqliteTable(
	"alg_subset",
	{
		id: text("id")
			.notNull()
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		slug: text("slug").notNull(),
		categoryId: text("category_id")
			.notNull()
			.references(() => algCategory.id),
		userId: text("user_id"),
		name: text("name").notNull(),
		sortOrder: integer("sort_order").default(0),
	},
	(t) => [uniqueIndex("alg_subset_slug_user_id_key").on(t.slug, t.userId)],
);

export const fsrsCardState = sqliteTable(
	"fsrs_card_state",
	{
		id: text("id")
			.notNull()
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		userId: text("user_id").notNull(),
		caseId: text("case_id")
			.notNull()
			.references(() => algCase.id),
		due: integer("due").notNull(),
		stability: real("stability"),
		difficulty: real("difficulty"),
		elapsedDays: integer("elapsed_days"),
		scheduledDays: integer("scheduled_days"),
		reps: integer("reps").default(0),
		lapses: integer("lapses").default(0),
		state: integer("state").default(0),
		lastReview: integer("last_review"),
		updatedAt: text("updated_at").$defaultFn(() => new Date().toISOString()),
	},
	(t) => [
		uniqueIndex("fsrs_card_state_user_id_case_id_key").on(t.userId, t.caseId),
	],
);

export const practiceTimeEntry = sqliteTable("practice_time_entry", {
	id: text("id")
		.notNull()
		.primaryKey()
		.$defaultFn(() => crypto.randomUUID()),
	userId: text("user_id").notNull(),
	caseId: text("case_id")
		.notNull()
		.references(() => algCase.id),
	ms: integer("ms").notNull(),
	reviewedAt: text("reviewed_at").$defaultFn(() => new Date().toISOString()),
});

export const userAlgAnnotation = sqliteTable(
	"user_alg_annotation",
	{
		userId: text("user_id").notNull(),
		caseId: text("case_id")
			.notNull()
			.references(() => algCase.id),
		recognition: text("recognition"),
		mnemonic: text("mnemonic"),
		notes: text("notes"),
		updatedAt: text("updated_at").$defaultFn(() => new Date().toISOString()),
	},
	(t) => [primaryKey({ columns: [t.userId, t.caseId] })],
);

export const userAlgSelection = sqliteTable(
	"user_alg_selection",
	{
		userId: text("user_id").notNull(),
		caseId: text("case_id")
			.notNull()
			.references(() => algCase.id),
	},
	(t) => [primaryKey({ columns: [t.userId, t.caseId] })],
);

export const userSettings = sqliteTable("user_settings", {
	userId: text("user_id").notNull().primaryKey(),
	currentCategoryId: text("current_category_id").references(
		() => algCategory.id,
	),
	currentCaseId: text("current_case_id").references(() => algCase.id),
	orderMode: text("order_mode").default("fsrs"),
	libOptions: text("lib_options"),
	fsrsParams: text("fsrs_params"),
	practiceTimeLimit: integer("practice_time_limit"),
	updatedAt: text("updated_at").$defaultFn(() => new Date().toISOString()),
});
