/**
 * AUTO-GENERATED FILE — DO NOT EDIT.
 *
 * Source: Postgres catalogs (schema: cubefsrs)
 * Generated by: oosync/src/codegen-schema.ts
 */

import { createBrowserSyncRuntime } from "oosync/runtime/browser-sqlite";
import { type SyncRuntime, setSyncRuntime } from "oosync/sync";
import * as localSchema from "../../../drizzle/schema-sqlite";
import {
	SYNCABLE_TABLES,
	TABLE_REGISTRY,
	TABLE_SYNC_ORDER,
	TABLE_TO_SCHEMA_KEY,
} from "../../../shared/table-meta";
import { browserSqliteClient } from "../db/client-sqlite";

let configured = false;

export function ensureSyncRuntimeConfigured(): void {
	if (configured) return;
	const runtime: SyncRuntime = createBrowserSyncRuntime({
		client: browserSqliteClient,
		schema: {
			syncableTables: SYNCABLE_TABLES,
			tableRegistry: TABLE_REGISTRY,
			tableSyncOrder: TABLE_SYNC_ORDER,
			tableToSchemaKey: TABLE_TO_SCHEMA_KEY,
		},
		localSchema,
	});
	setSyncRuntime(runtime);
	configured = true;
}

ensureSyncRuntimeConfigured();
