#!/usr/bin/env python3
"""
Generate supabase/seeds/01_global_catalog.sql from src/data/defaultAlgs.json.

UUIDs are deterministically generated using uuid5 (namespace = project UUID +
path components) so the file is idempotent and diffable in git.
"""

import json
import re
import uuid
from pathlib import Path

# ── Paths ────────────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent.parent
SRC_DATA = REPO_ROOT / "src" / "data" / "defaultAlgs.json"
OUT_FILE = SCRIPT_DIR.parent / "seeds" / "01_global_catalog.sql"

# ── Deterministic UUID helpers ────────────────────────────────────────────────
# Stable namespace so running the script twice always produces the same UUIDs.
NS = uuid.UUID("f47ac10b-58cc-4372-a567-0e02b2c3d479")  # arbitrary fixed namespace


def make_uuid(path: str) -> str:
    """Return a deterministic UUID string derived from `path`."""
    return str(uuid.uuid5(NS, path))


# ── Slug helpers ──────────────────────────────────────────────────────────────

def slugify(text: str) -> str:
    """Convert human-readable text to a URL-safe slug."""
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)  # non-alphanumeric → hyphen
    text = re.sub(r"-+", "-", text)           # collapse runs of hyphens
    return text.strip("-")


# ── SQL helpers ───────────────────────────────────────────────────────────────

def sql_str(value: str | None) -> str:
    """Return a SQL literal for a string value (NULL if None)."""
    if value is None:
        return "NULL"
    # Escape single quotes by doubling them.
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


# ── Main generation ───────────────────────────────────────────────────────────

def generate() -> None:
    with SRC_DATA.open() as f:
        data: dict[str, list] = json.load(f)

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    cat_rows: list[str] = []
    sub_rows: list[str] = []
    case_rows: list[str] = []

    for cat_order, (cat_name, subsets) in enumerate(data.items()):
        cat_slug = slugify(cat_name)
        cat_id = make_uuid(f"cat:{cat_slug}")

        cat_rows.append(
            f"  ({sql_str(cat_id)}, {sql_str(cat_slug)}, NULL, {sql_str(cat_name)}, {cat_order})"
        )

        for sub_order, subset_obj in enumerate(subsets):
            sub_name: str = subset_obj["subset"]
            # Prefix with category slug to keep subset slugs globally unique.
            sub_slug = f"{cat_slug}-{slugify(sub_name)}"
            sub_id = make_uuid(f"sub:{sub_slug}")

            sub_rows.append(
                f"  ({sql_str(sub_id)}, {sql_str(sub_slug)}, {sql_str(cat_id)}, NULL, {sql_str(sub_name)}, {sub_order})"
            )

            for alg_order, alg_obj in enumerate(subset_obj["algorithms"]):
                alg_name: str = alg_obj["name"]
                alg_str: str = alg_obj.get("algorithm", "")
                # Prefix with subset slug to keep case slugs globally unique.
                case_slug = f"{sub_slug}-{slugify(alg_name)}"
                # Disambiguate if two algs in the same subset share a name after slugify.
                dedup_path = f"case:{case_slug}:{alg_order}"
                case_id = make_uuid(dedup_path)

                case_rows.append(
                    f"  ({sql_str(case_id)}, {sql_str(case_slug)}, {sql_str(sub_id)}, NULL, {sql_str(alg_name)}, {sql_str(alg_str)}, {alg_order})"
                )

    lines: list[str] = [
        "-- =============================================================================",
        "-- CubeFSRS: Global Algorithm Catalog Seed",
        "-- Generated by supabase/scripts/gen_seed.py — DO NOT EDIT BY HAND.",
        "-- Run `python3 supabase/scripts/gen_seed.py` to regenerate.",
        "-- =============================================================================",
        "",
        "-- Categories (" + str(len(cat_rows)) + " rows) ─────────────────────────────",
        "INSERT INTO cubefsrs.alg_category (id, slug, user_id, name, sort_order)",
        "VALUES",
        ",\n".join(cat_rows),
        "ON CONFLICT (id) DO NOTHING;",
        "",
        "-- Subsets (" + str(len(sub_rows)) + " rows) ──────────────────────────────────",
        "INSERT INTO cubefsrs.alg_subset (id, slug, category_id, user_id, name, sort_order)",
        "VALUES",
        ",\n".join(sub_rows),
        "ON CONFLICT (id) DO NOTHING;",
        "",
        "-- Cases (" + str(len(case_rows)) + " rows) ───────────────────────────────────",
        "INSERT INTO cubefsrs.alg_case (id, slug, subset_id, user_id, name, alg, sort_order)",
        "VALUES",
        ",\n".join(case_rows),
        "ON CONFLICT (id) DO NOTHING;",
        "",
    ]

    OUT_FILE.write_text("\n".join(lines))
    print(f"Wrote {OUT_FILE}")
    print(f"  Categories : {len(cat_rows)}")
    print(f"  Subsets    : {len(sub_rows)}")
    print(f"  Cases      : {len(case_rows)}")


if __name__ == "__main__":
    generate()
