/**
 * AUTO-GENERATED FILE — DO NOT EDIT.
 *
 * Source: Postgres catalogs (schema: cubefsrs)
 * Generated by: oosync/src/codegen-schema.ts
 */

import {
	type SyncableTableName as GeneratedSyncableTableName,
	SYNCABLE_TABLES as SYNCABLE_TABLES_GENERATED,
	TABLE_REGISTRY_CORE,
	type TableMetaCore,
} from "./generated/sync/table-meta.generated";

export type ChangeCategory = string | null;
export type SyncableTableName = GeneratedSyncableTableName;

export interface TableMeta {
	primaryKey: string | string[];
	uniqueKeys: string[] | null;
	timestamps: string[];
	booleanColumns: string[];
	supportsIncremental: boolean;
	hasDeletedFlag: boolean;
	changeCategory: ChangeCategory;
	normalize?: (row: Record<string, unknown>) => Record<string, unknown>;
	columnDescriptions?: Record<string, string>;
}

export const SYNCABLE_TABLES = SYNCABLE_TABLES_GENERATED;

function normalizeDatetimeFields(
	row: Record<string, unknown>,
	fields: string[],
): Record<string, unknown> {
	const normalized = { ...row };
	for (const field of fields) {
		const value = normalized[field];
		if (typeof value === "string") {
			let result = value.includes(" ") ? value.replace(" ", "T") : value;
			if (/Z$/i.test(result) || /[+-]\d{2}:?\d{2}$/.test(result)) {
				normalized[field] = result;
				continue;
			}
			if (/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/.test(result)) {
				result = `${result}Z`;
			}
			normalized[field] = result;
		}
	}
	return normalized;
}

const TABLE_EXTRAS: Record<
	SyncableTableName,
	Pick<TableMeta, "changeCategory" | "normalize" | "columnDescriptions">
> = {
	alg_case: {
		changeCategory: "catalog",
		normalize: (row) =>
			normalizeDatetimeFields(row, ["created_at", "updated_at"]),
	},
	alg_category: {
		changeCategory: "catalog",
	},
	alg_subset: {
		changeCategory: "catalog",
	},
	fsrs_card_state: {
		changeCategory: "practice",
		normalize: (row) => normalizeDatetimeFields(row, ["updated_at"]),
	},
	practice_time_entry: {
		changeCategory: "practice",
		normalize: (row) => normalizeDatetimeFields(row, ["reviewed_at"]),
	},
	user_alg_annotation: {
		changeCategory: "user",
		normalize: (row) => normalizeDatetimeFields(row, ["updated_at"]),
	},
	user_alg_selection: {
		changeCategory: "user",
	},
	user_settings: {
		changeCategory: "user",
		normalize: (row) => normalizeDatetimeFields(row, ["updated_at"]),
	},
};

export const TABLE_REGISTRY_MERGED: Record<SyncableTableName, TableMeta> =
	Object.fromEntries(
		Object.entries(TABLE_REGISTRY_CORE).map(([tableName, core]) => {
			const extras = TABLE_EXTRAS[tableName as SyncableTableName];
			return [tableName, { ...(core as TableMetaCore), ...extras }];
		}),
	) as Record<SyncableTableName, TableMeta>;

export const TABLE_REGISTRY: Record<string, TableMeta> = TABLE_REGISTRY_MERGED;

function getRequiredMeta(tableName: string): TableMeta {
	const meta = TABLE_REGISTRY[tableName];
	if (!meta) {
		throw new Error(`Unknown table: ${tableName}`);
	}
	return meta;
}

export const COMPOSITE_PK_TABLES: SyncableTableName[] = (() => {
	const tables: SyncableTableName[] = [];
	for (const tableName of SYNCABLE_TABLES) {
		const pk = TABLE_REGISTRY_MERGED[tableName].primaryKey;
		if (Array.isArray(pk)) {
			tables.push(tableName);
		}
	}
	return tables;
})();

export const NON_STANDARD_PK_TABLES: Partial<
	Record<SyncableTableName, string>
> = (() => {
	const map: Partial<Record<SyncableTableName, string>> = {};
	for (const tableName of SYNCABLE_TABLES) {
		const pk = TABLE_REGISTRY_MERGED[tableName].primaryKey;
		if (typeof pk === "string" && pk !== "id") {
			map[tableName] = pk;
		}
	}
	return map;
})();

export function getPrimaryKey(tableName: string): string | string[] {
	const pk = getRequiredMeta(tableName).primaryKey;
	return Array.isArray(pk) ? [...pk] : pk;
}

export function getUniqueKeys(tableName: string): string[] | null {
	const uniqueKeys = getRequiredMeta(tableName).uniqueKeys;
	return uniqueKeys ? [...uniqueKeys] : null;
}

export function getConflictTarget(tableName: string): string[] {
	const meta = getRequiredMeta(tableName);
	if (meta.uniqueKeys) return [...meta.uniqueKeys];

	const pk = meta.primaryKey;
	return Array.isArray(pk) ? [...pk] : [pk];
}

export function supportsIncremental(tableName: string): boolean {
	return TABLE_REGISTRY[tableName]?.supportsIncremental ?? false;
}

export function hasDeletedFlag(tableName: string): boolean {
	return TABLE_REGISTRY[tableName]?.hasDeletedFlag ?? false;
}

export function getBooleanColumns(tableName: string): string[] {
	return [...(TABLE_REGISTRY[tableName]?.booleanColumns ?? [])];
}

export function getNormalizer(
	tableName: string,
):
	| ((row: Readonly<Record<string, unknown>>) => Record<string, unknown>)
	| undefined {
	const normalize = TABLE_REGISTRY[tableName]?.normalize;
	return normalize
		? (row) => normalize(row as Record<string, unknown>)
		: undefined;
}

export function isRegisteredTable(tableName: string): boolean {
	return tableName in TABLE_REGISTRY;
}

export function hasCompositePK(tableName: string): boolean {
	return Array.isArray(TABLE_REGISTRY[tableName]?.primaryKey);
}

export function buildRowIdForOutbox(
	tableName: string,
	row: Readonly<Record<string, unknown>>,
): string {
	const pk = getPrimaryKey(tableName);
	if (Array.isArray(pk)) {
		const keyObj: Record<string, unknown> = {};
		for (const col of pk) {
			keyObj[col] = row[col];
		}
		return JSON.stringify(keyObj);
	}
	return String(row[pk]);
}

export function parseOutboxRowId(
	tableName: string,
	rowId: string,
): Record<string, unknown> | string {
	const pk = getPrimaryKey(tableName);
	if (Array.isArray(pk)) {
		try {
			return JSON.parse(rowId) as Record<string, unknown>;
		} catch {
			throw new Error(
				`Invalid JSON row_id for composite key table ${tableName}: ${rowId}`,
			);
		}
	}
	return rowId;
}

export const TABLE_SYNC_ORDER: Record<string, number> = {
	alg_case: 3,
	alg_category: 1,
	alg_subset: 2,
	fsrs_card_state: 4,
	practice_time_entry: 5,
	user_alg_annotation: 6,
	user_alg_selection: 7,
	user_settings: 8,
};

export const TABLE_TO_SCHEMA_KEY: Record<string, string> = {
	alg_case: "algCase",
	alg_category: "algCategory",
	alg_subset: "algSubset",
	fsrs_card_state: "fsrsCardState",
	practice_time_entry: "practiceTimeEntry",
	user_alg_annotation: "userAlgAnnotation",
	user_alg_selection: "userAlgSelection",
	user_settings: "userSettings",
};
